name: deploy-test
run-name: deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh-scp-ssh-pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: ${{ secrets.IP  }}
        user: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        first_ssh: |
          ./update.sh
